### ISSUE TITLE
Lizzy deletes the newly deployed stack instead of the old one

### ISSUE THREAD

**Issue by ePaul** [zalando/lizzy#106]
We just discovered a bug.

**Wrong behavior**

We use lizzy to deploy our created docker image artifact from Jenkins to our Staging AWS account. The Docker tag versions are named 0.1.‹build number›, and the build number just changed from 97 to 100 (and then 101, 102, ...). For the versions 100 and following, we can see in the cloud formation logs that these stacks were created and right afterward deleted again (after the traffic was switched to them, unfortunately), with version 97 still running.

Our Jenkins Job uses `lizzy create -v --traffic 100 warehouse-allocation.yaml $docker_tag`, where $docker_tag is e.g. `0.1.101`.

**Expected behavior**
The old stack should be deleted, not the just deployed one.

**Comment by ePaul** [comment]
It looks like Lizzy sorts the existing stacks lexicographically, and deletes the smallest ones.
`0.1.101` (or `0o1o101T...` as the stack is named on AWS) is lower than `0.1.97` (`0o1o97T...`).

The ordering should either just look at the timestamp (the part after the `T`), or sort by component numerically. Or just don't delete the newly created stack.

**Comment by jmcs** [comment]
Are you using the latest lizzy version? We had that bug in the past, but [currently it is sorting by creation date](https://github.com/zalando/lizzy/blob/master/lizzy/job/deployer.py#L139).

**Comment by ePaul** [comment]
Not sure, the Jenkins job console log says "Client: 2016-01-14, Server: 2016-02-22".
Seeing that the latest releases are some hours ago, I would say no.
