### ISSUE TITLE
Register kio version in the client

### ISSUE THREAD

**Issue by jmcs** [zalando/lizzy#120]
The kio version should be registered on the client not on the server side.

**Comment by jmcs** [comment]
@rafaelcaricio @lotharschulz should we make this out of scope for lizzy 2.0\Model Z?

**Comment by rafaelcaricio** [comment]
@jmcs I see you commit'ed some changes. Do you found some corner case on having it at Model Z?

**Comment by jmcs** [comment]
No, but since `kio` can run with same credentials as `lizzy-client` and `senza` anyway maybe is better for users to call it explicitly, that way we reduce complexity and avoid problems in `lizzy` due to changes in `kio` and it's easier to support more complex cases like when a stack has more than one application.

**Comment by rafaelcaricio** [comment]
I see. It sounds good then to keep it separated.

Maybe it is a good idea to move all `kio` calls and make them happen in a plugin to ModelZ using entrypoints? It could be that ModelZ would work exactly like `senza` but you can add plugins to extend the behaviour.

**Comment by rafaelcaricio** [comment]
I guess we have decided to move it completely out of Lizzy. So I will close this issue for now.
