### ISSUE TITLE
Provide a schema-discovery endpoint for Twintip 

### ISSUE THREAD

**Issue by lerovitch** [zalando/lizzy#124]
In order to automatically collect API definition from Twintip the following endpoint needs to be provided by [Twintip](https://myapp.example.com/.well-known/schema-discovery) 
```
https://myapp.example.com/.well-known/schema-discovery
```

It would be a good idea if it doesn't require an OAuth token

**Comment by hjacobs** [comment]
for reference: https://zalando.github.io/restful-api-guidelines/api-discovery/ApiDiscovery.html

**Comment by rafaelcaricio** [comment]
Fixed by #127
