### ISSUE TITLE
Better documentation

### ISSUE THREAD

**Issue by zmeda** [zalando/lizzy#13]
Hi!

I have no idea how to use this tool. So please provide better documentation and also some examples. I'm specially interested in using it within Continuous Delivery.

Thanks!

**Comment by hjacobs** [comment]
:+1:

**Comment by dmitrykrivaltsevich** [comment]
Could you please also describe how to build a docker image with lizzy

**Comment by drummerwolli** [comment]
+1 ... no senza yaml file for lizzy itself ...
