### ISSUE TITLE
Remove old stacks even if they are not in Redis

### ISSUE THREAD

**Issue by kaygorodov** [zalando/lizzy#136]
The way _--keep-stack 0_ currently works is that it deletes only those stacks which are represented in Redis.

It would be useful to have a possibility to remove all stacks of an app regardless of their presence in Redis.

**Comment by hjacobs** [comment]
I think the plan is to get rid of Redis altogether, this would solve your problem...

**Comment by rafaelcaricio** [comment]
Yes, the version of lizzy under the tag `release2.0` does not depend on redis.
