### ISSUE TITLE
CF stack not being removed by Lizzy

### ISSUE THREAD

**Issue by rafaelcaricio** [zalando/lizzy#147]
***Applies to `release2.0` branch.***

When executing:

```
$ lizzy-client delete hello-bus bus31 --region eu-west-1
```

The lizzy agent logs:
```
 INFO: Removing stack hello-bus-bus31...
DEBUG: Executing senza.
     > command: senza delete --region eu-west-1 hello-bus-bus31
 INFO: Stack hello-bus-bus31 removed.
DEBUG: Getting data and status code
     > data_type: <class 'tuple'>
     > url: http://192.168.99.100:8080/api/stacks/hello-bus-bus31
     > data: ('', 204, {'X-Lizzy-Version': '2.0', 'x-Lizzy-Output': ''})
DEBUG: Got data and status code (204)
     > data_type: <class 'str'>
     > url: http://192.168.99.100:8080/api/stacks/hello-bus-bus31
     > data: ************ EMPTY ************
DEBUG: Endpoint returned an empty response (204)
     > url: http://192.168.99.100:8080/api/stacks/hello-bus-bus31
     > mimetype: application/json
UWSGI: DELETE /api/stacks/hello-bus-bus31 -> 204
```

Which runs the senza command `senza delete --region eu-west-1 hello-bus-bus31` that does not do anything (and senza does not return code 1). So Lizzy returns http code 204 as the stack was deleted, but actually it was not.

### Expected behaviour

Lizzy agent should run the command `senza delete --region eu-west-1 hello-bus bus31` (with space between stack name and stack version) so senza will delete the stack. Plus would be nice to fix Senza cli to return code 1 when calling delete subcommand and the stack does not exist.

**Comment by kaygorodov** [comment]
I ran into this problem as well.

**Comment by rafaelcaricio** [comment]
Fixed in `release2.0`.
