### ISSUE TITLE
Consider format for commit messages to avoid violations ("fullstop").

### ISSUE THREAD

**Issue by dmitrykrivaltsevich** [zalando/lizzy#154]
When I deploy lizzy-server into my AWS account, I always get a violation from "fullstop":

```json
{
        "account_id": "<my-aws-account-id>",
        "comment": null,
        "created_time": 1467297289.153,
        "id": "<my-violation-id>",
        "instance_id": null,
        "meta_info": "application_id: lizzy-stt, invalid_commits: 5b0f45b672d9af8f210b73107121ebf57792d36c,     (Use application_id from Taupa...), repository: 'https://github.com/zalando/lizzy'",
        "region": "<my-aws-region>",
        "violation_type": "MISSING_SPEC_LINKS"
}
```

Seems that comment message should has a prefix referenced to issue number. Usually we put JIRA-XXXX, but I'm not 100% sure what is necessary for open-sourced projects. Maybe we should consider a format for comments in order to avoid violations.

**Comment by rafaelcaricio** [comment]
I am aware of that. We were just discussing that today. The simplest way for now is that we will try to watch out add the GH issue number in the future in the commit messages until the compliance rules change.

Please close the violation adding the link to this PR https://github.com/zalando/lizzy/pull/152 and you should be fine. Sorry for the inconvenience.

**Comment by rafaelcaricio** [comment]
@dmitrykrivaltsevich I have added Zappr config to validate that in #155.
