### ISSUE TITLE
Add senza's --parameter-file option to lizzy

### ISSUE THREAD

**Issue by drummerwolli** [zalando/lizzy#174]
introduced with https://github.com/zalando-stups/senza/pull/227 and senza 1.0.66 https://github.com/zalando-stups/senza/releases/tag/1.0.66

lizzy and lizzy-client should be able to work with those.

**Comment by drummerwolli** [comment]
any estimate when you have time to work on this?

**Comment by cgmv** [comment]
Please add this feature as soon as possible - currently stops switch to Jenkinsfile based approach.
