### ISSUE TITLE
Include stack name parameter replacement

### ISSUE THREAD

**Issue by marius-oexle** [zalando/lizzy#176]
When trying to deploy a stack with an additional parameter to be replaced in the stack name, an error is thrown:
[AGENT] Stack not found: someservice-staging-{{Arguments.Type}}-XX
Please add the stack name to the list of modifyable attributes so placeholders like above are correctly replaced.

**Comment by rafaelcaricio** [comment]
We do not support replacement in `StackName` field. That is more of a Senza issue, already described in https://github.com/zalando-stups/senza/issues/145.
