### ISSUE TITLE
Lizzy wait too long for Senza command on traffic change

### ISSUE THREAD

**Issue by rafaelcaricio** [zalando/lizzy#194]
Lizzy calls Senza to change traffic and sometimes it takes too long. https://github.com/zalando-stups/senza/pull/420
We need a new option in Senza traffic command to **not** wait the stacks to be ready and fail fast if it is not possible to change the traffic immediately. That way Lizzy will also fail, but the lizzy-client can keep trying to perform the change.

**Comment by mrandi** [comment]
@rafaelcaricio actually we would even prefer to have a longer timeout. Depending if the traffic switch went well we are normally deleting the old stacks.
Because of this we have a lot of old stacks still running, our pipeline doesn't know if the traffic was switched or not and just terminate.

**Comment by rafaelcaricio** [comment]
@mrandi The https://github.com/zalando-stups/senza/pull/447 should do the trick from the Senza side. Then we can add the same options to Lizzy and let you control how you want to execute the traffic change.

**Comment by mrandi** [comment]
@rafaelcaricio just ping when you got some time to finish this, it would really help us out!

**Comment by rafaelcaricio** [comment]
This was fixed in the Senza version [2.1.66](https://github.com/zalando-stups/senza/releases/tag/2.1.66).

**Comment by rafaelcaricio** [comment]
The latest docker images of Lizzy already have this new version of Senza. So this problem should not happen again.

**Comment by rafaelcaricio** [comment]
@mrandi Could you please upgrade your lizzy instance and check if this issue is still persisting? If not, I would like to close this.

**Comment by mrandi** [comment]
@rafaelcaricio working now! can be closed.
Thanks

**Comment by rafaelcaricio** [comment]
Thank you!
