### ISSUE TITLE
Tag cloud formation stacks

### ISSUE THREAD

**Issue by jmcs** [zalando/lizzy#31]
Every cloud formation stack created via lizzy should be tagged, this way it will be possible to find them even if the redis database is lost.

**Comment by jmcs** [comment]
Requirements should be changed to ensure senza's version is equal or superior to [1.0.40](https://github.com/zalando-stups/senza/releases/tag/1.0.40).

**Comment by jmcs** [comment]
@rafaelcaricio I think it's useful to tag the lizzy version used and perhaps also tag older tags during the job so we know which stacks were created by Lizzy. WDYT?

**Comment by rafaelcaricio** [comment]
@jmcs Sounds like a good idea.
