### ISSUE TITLE
The log is overloaded with...

### ISSUE THREAD

**Issue by zmeda** [zalando/lizzy#38]
The `application.log` on lizzy EC2 instance is every 5 seconds populated with output like:

    Dec 14 11:34:09 ip-172-31-153-151 docker/435e7ca88f70[784]: DEBUG: In Job
    Dec 14 11:34:09 ip-172-31-153-151 docker/435e7ca88f70[784]: DEBUG: Waiting 15 seconds to run the job again.
    Dec 14 11:34:09 ip-172-31-153-151 docker/435e7ca88f70[784]: DEBUG: Getting all lizzy_stack
    Dec 14 11:34:09 ip-172-31-153-151 docker/435e7ca88f70[784]: DEBUG: Executing senza.
    Dec 14 11:34:09 ip-172-31-153-151 docker/435e7ca88f70[784]:      > command: senza list --region eu-west-1 -o json
    Dec 14 11:34:10 ip-172-31-153-151 docker/435e7ca88f70[784]: *** SIGNAL QUEUE IS FULL: buffer size 212992 bytes (you can tune it with --signal-bufsize)     ***
    Dec 14 11:34:10 ip-172-31-153-151 docker/435e7ca88f70[784]: could not deliver signal 42 to mule 1
    Dec 14 11:34:10 ip-172-31-153-151 docker/435e7ca88f70[784]: UWSGI: GET /api/swagger.json -> 200
    Dec 14 11:34:15 ip-172-31-153-151 docker/435e7ca88f70[784]: *** SIGNAL QUEUE IS FULL: buffer size 212992 bytes (you can tune it with --signal-bufsize)     ***
    Dec 14 11:34:15 ip-172-31-153-151 docker/435e7ca88f70[784]: could not deliver signal 42 to mule 1
    Dec 14 11:34:17 ip-172-31-153-151 docker/435e7ca88f70[784]: UWSGI: GET /api/swagger.json -> 200
    Dec 14 11:34:20 ip-172-31-153-151 docker/435e7ca88f70[784]: *** SIGNAL QUEUE IS FULL: buffer size 212992 bytes (you can tune it with --signal-bufsize)     ***
    Dec 14 11:34:20 ip-172-31-153-151 docker/435e7ca88f70[784]: could not deliver signal 42 to mule 1
    Dec 14 11:34:20 ip-172-31-153-151 docker/435e7ca88f70[784]: UWSGI: GET /api/swagger.json -> 200

It is really hard to find something useful in the log when needed.

**Comment by jmcs** [comment]
There is already an issue (#35) to make log level configurable please watch that issue.
