### ISSUE TITLE
Support for senza patch & senza respawn-instances

### ISSUE THREAD

**Issue by priesus** [zalando/lizzy#41]
It would be great to be able to fully automate Taupage image updates of CloudFormation stacks we're already deploying with Lizzy.

Currently we have a shell script that does this for all our stacks:
```
senza patch <stackname> <stackversion> --image=latest
senza respawn-instances <stackname> <stackversion>
```
Ideally a scheduled Jenkins jobs could do this without manual interaction.

**Comment by jmcs** [comment]
:+1:

**Comment by jmcs** [comment]
The best way to implement this is to add an image argument to [api.patch](https://github.com/zalando/lizzy/blob/master/lizzy/api.py#L161) and apply the change immediately. Later we can add instance-type and user-data, that senza [also supports](https://github.com/zalando-stups/senza/blob/master/senza/cli.py#L1237).

@rafaelcaricio maybe you can also move the [traffic changing part of the job](https://github.com/zalando/lizzy/blob/master/lizzy/job/deployer.py#L132) to api.patch and remove the `LIZZY:CHANGE` state from the Deployer.handle.

**Comment by rafaelcaricio** [comment]
@jmcs Please check the PR #47.

I think the code move of `LIZZY:CHANGE` I will send in a new PR since this one is already too big. What do you think?

**Comment by jmcs** [comment]
I'm going to check the PR. I agree the Pull Request is already quite large so it's better to leave further refactoring for another PR.
