### ISSUE TITLE
Support named parameters

### ISSUE THREAD

**Issue by jmcs** [zalando/lizzy#70]
Senza supports named parameters, but lizzy's definition parser still doesn't.

**Comment by rafaelcaricio** [comment]
@jmcs Could you elaborate on that issue? I am willing to take care of it.

**Comment by rafaelcaricio** [comment]
http://docs.stups.io/en/latest/components/senza.html#senza-info

**Comment by jmcs** [comment]
Right now lizzy only supports providing arguments in the order they were given in senza definition, but senza also supports setting arguments in the form of `KEY=VALUE` for example:

    $ senza create example.yaml 3 example MintBucket=<mint-bucket> ImageVersion=latest

One important note from the documentation is that:

    The name=value named parameters are split on first = which makes it possible to still
    include a literal = in the value part. This also means that if you have to include it in 
    the parameter value, you need to pass this parameter with the name, to prevent 
    senza from treating the part of the parameter value before the first = as the
    parameter name.

**Comment by rafaelcaricio** [comment]
@jmcs Is this not already supported by https://github.com/zalando/lizzy/blob/master/lizzy/swagger/lizzy.yaml#L265-L269 ?

**Comment by jmcs** [comment]
I think we don't support it when parsing the yaml file to extract the docker image. If the docker image name is set with a named parameter it can fail.
