### ISSUE TITLE
ImageVersion prepended to senza parameters

### ISSUE THREAD

**Issue by mfelsche** [zalando/lizzy#99]
The way lizzy currently assembles `senza create` calls it prepends the image_version argument as first param to the call.
turning: 
`lizzy create senza.yaml <image_version> SenzaParam1=foo SenzaParam2=bar` into `senza create senza.yaml <image_version> SenzaParam1=foo SenzaParam2=bar`.

This requires the senza definition to have a param denothing the docker image version as first paramater, which makes lizzy less flexible.

We have a bunch of senza configs which have different first parameters and we plan on creating some that don't even need an `ImageVersion`.

I'd vote for removing the image_version param from client and lizzy completely and grepping the image_version from params or taupage config, thus making it optional.

What do you think?

**Comment by rafaelcaricio** [comment]
In the current master version of Lizzy it does not make that assumption anymore.
